# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWind.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.url_text_line_edit = QtWidgets.QLineEdit(Form)
        self.url_text_line_edit.setGeometry(QtCore.QRect(60, 50, 231, 31))
        self.url_text_line_edit.setObjectName("url_text_line_edit")
        self.analyze_btn = QtWidgets.QPushButton(Form)
        self.analyze_btn.setGeometry(QtCore.QRect(300, 50, 81, 31))
        self.analyze_btn.setObjectName("analyze_btn")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(60, 263, 311, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.download_btn = QtWidgets.QPushButton(Form)
        self.download_btn.setGeometry(QtCore.QRect(20, 210, 101, 31))
        self.download_btn.setObjectName("download_btn")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(23, 110, 41, 21))
        self.label_3.setObjectName("label_3")
        self.novel_name_edit = QtWidgets.QLineEdit(Form)
        self.novel_name_edit.setGeometry(QtCore.QRect(80, 109, 221, 21))
        self.novel_name_edit.setObjectName("novel_name_edit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 146, 51, 20))
        self.label_4.setObjectName("label_4")
        self.chapter_count = QtWidgets.QLabel(Form)
        self.chapter_count.setGeometry(QtCore.QRect(80, 147, 201, 20))
        self.chapter_count.setObjectName("chapter_count")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 31, 21))
        self.label_5.setObjectName("label_5")
        self.status_label = QtWidgets.QLabel(Form)
        self.status_label.setGeometry(QtCore.QRect(80, 170, 201, 21))
        self.status_label.setObjectName("status_label")
        self.continue_download_btn = QtWidgets.QPushButton(Form)
        self.continue_download_btn.setGeometry(QtCore.QRect(280, 210, 101, 31))
        self.continue_download_btn.setDefault(False)
        self.continue_download_btn.setFlat(False)
        self.continue_download_btn.setObjectName("continue_download_btn")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(370, 0, 31, 31))
        self.exit_btn.setObjectName("exit_btn")
        self.stop_download_btn = QtWidgets.QPushButton(Form)
        self.stop_download_btn.setGeometry(QtCore.QRect(150, 210, 101, 31))
        self.stop_download_btn.setObjectName("stop_download_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "小说下载器"))
        self.label.setText(_translate("Form", "URL："))
        self.analyze_btn.setText(_translate("Form", "分析"))
        self.label_2.setText(_translate("Form", "进度:"))
        self.download_btn.setText(_translate("Form", "开始"))
        self.label_3.setText(_translate("Form", "小说名:"))
        self.label_4.setText(_translate("Form", "章节数:"))
        self.chapter_count.setText(_translate("Form", "未知"))
        self.label_5.setText(_translate("Form", "状态:"))
        self.status_label.setText(_translate("Form", "未知"))
        self.continue_download_btn.setText(_translate("Form", "继续"))
        self.exit_btn.setText(_translate("Form", "退出"))
        self.stop_download_btn.setText(_translate("Form", "暂停"))
